# Generated by Django 5.1.4 on 2024-12-30 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IspKeywords',
            fields=[
                ('term', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('searches', models.IntegerField()),
                ('orders', models.IntegerField()),
                ('sales', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
            options={
                'db_table': 'isp_keywords',
            },
        ),
    ]
